# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

configfile: "config/config.yaml"

# Find sample directory names
BARCODES = [name for name in os.listdir("data/long-read")]
print("You have provided long-read data with the following IDs:", BARCODES)

# Load rules
include: "rules/filtlong.smk"
include: "rules/flye.smk"
include: "rules/medaka.smk"
include: "rules/download_homopolish_sketch.smk"
include: "rules/homopolish.smk"
include: "rules/polypolish.smk"
include: "rules/quast.smk"

# Target rules
rule homopolish_workflow:
    input:
        #quast_reports  = expand("results/main/quast_reports/html_reports/{bc}_quast.html", bc = BARCODES),
        homopolish = expand("results/main/{bc}/homopolish_assembly/{bc}_assembly_flye_medaka_homopolish.fna", bc = BARCODES)
