# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

# Find sample directory names
BARCODES = [name for name in os.listdir("data/long-read-seq-sup")]
print(BARCODES)

# Load helper functions
include: "rules/common.smk"

# Load rules
include: "rules/filtlong.smk"
include: "rules/flye.smk"
include: "rules/medaka.smk"
include: "rules/homopolish.smk"
include: "rules/quast.smk"

# Target rule
rule all:
    input:
        quast_reports  = expand("results/main/quast_reports/html_reports/{bc}_quast.html", bc = BARCODES),
        #homopolish = expand("results/intermediate/{bc}/homopolish_assembly/{bc}_assembly_flye_medaka_homopolish.fasta", bc = BARCODES)
